### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by sidequestlegend**

### CODE REVIEW

**Comment by mikeskydev** [comment]
Can you bump package.json to 2.5.1 or 2.6?

**Comment by sidequestlegend** [comment]
is there something special needed for the samples to work on UPM?

**Comment by mikeskydev** [comment]
I'll need to edit my code when I'm back, it tries to push the folder name change to `main` but it doesn't have permissions. For now, you could create a separate branch from `main` after this merge, change the folder name manually, then tag that branch with 2.5.1

**Review by mikeskydev — APPROVED** [review]

**Comment by sidequestlegend** [comment]
Done! Thank you! https://github.com/SideQuestVR/BanterSDK/releases/tag/2.5.1

**Pull request merged**
